### ISSUE TITLE
How to get the min/max_geo_loc

### ISSUE THREAD

**Issue by wowlza** [Tsinghua-MARS-Lab/neural_map_prior#17]
Hello, thanks for the great work!
I have learned the code and have a question in  `lane_render.py`: the code tried to get the map_geo_loc  with the following code, 
```
train_min_geo_loc = {'singapore-onenorth': np.array([118., 420.]) - bev_radius,
                     'boston-seaport': np.array([298., 328.]) - bev_radius,
                     'singapore-queenstown': np.array([347., 862.]) - bev_radius,
                     'singapore-hollandvillage': np.array([442., 902.]) - bev_radius}
train_max_geo_loc = {'singapore-onenorth': np.array([1232., 1777.]) + bev_radius,
                     'boston-seaport': np.array([2527., 1896.]) + bev_radius,
                     'singapore-queenstown': np.array([2686., 3298.]) + bev_radius,
                     'singapore-hollandvillage': np.array([2490., 2839.]) + bev_radius}
val_min_geo_loc = {'singapore-onenorth': np.array([118., 408.]) - bev_radius,
                   'boston-seaport': np.array([412., 555.]) - bev_radius,
                   'singapore-queenstown': np.array([524., 871.]) - bev_radius,
                   'singapore-hollandvillage': np.array([608., 2007.]) - bev_radius}
val_max_geo_loc = {'singapore-onenorth': np.array([1232., 1732.]) + bev_radius,
                   'boston-seaport': np.array([2367., 1720.]) + bev_radius,
                   'singapore-queenstown': np.array([2044., 3333.]) + bev_radius,
                   'singapore-hollandvillage': np.array([2460., 2836.]) + bev_radius}

```
I'm not quite sure how to obtain these specific values (such as np.array([118., 420.]),  I tried to locate them in the nuscenes-devkit based on these values, but I couldn't find the corresponding points. 

Could you please explain what these values mean? And how were they obtained?

Thanks a lot !

**Comment by abbyxxn** [comment]
Thank you for your interest in our project. In our project, we need to build a global map, and since the samples in the nuscene are distributed across four cities, we need to create a separate global map for each city. 'min_geo_loc' and 'max_geo_loc' are the geographic coordinates of the top-left and bottom-right of the virtual global map, respectively. Setting these geographic coordinates ensures that the online maps constructed for each sample in the dataset can be recorded based on the geographic location of the sample as a prior. I have uploaded the code for calculating these two variables [here](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/project/neural_map_prior/data_utils/nuscenes_geo_loc.py).
